package com.cognizant.uams.service;

import com.cognizant.uams.entity.AcademicRecord;
import com.cognizant.uams.entity.Course;
import com.cognizant.uams.entity.Student;
import com.cognizant.uams.repository.AcademicRecordRepository;
import com.cognizant.uams.repository.CourseRepository;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;
import java.nio.charset.StandardCharsets;
import java.time.LocalDate;
import java.util.*;

@Service
public class TranscriptService {
    private static final Map<String, Double> GRADE_POINTS = Map.ofEntries(
            Map.entry("A+", 4.0), Map.entry("A", 4.0), Map.entry("A-", 3.7),
            Map.entry("B+", 3.3), Map.entry("B", 3.0), Map.entry("B-", 2.7),
            Map.entry("C+", 2.3), Map.entry("C", 2.0), Map.entry("C-", 1.7),
            Map.entry("D", 1.0), Map.entry("F", 0.0));

    private final AcademicRecordRepository academicRecordRepository;
    private final CourseRepository courseRepository;
    private final StudentService studentService;

    public TranscriptService(AcademicRecordRepository academicRecordRepository, CourseRepository courseRepository,
                             StudentService studentService) {
        this.academicRecordRepository = academicRecordRepository;
        this.courseRepository = courseRepository;
        this.studentService = studentService;
    }

    public List<AcademicRecord> getAcademicRecord(Integer studentId) {
        studentService.getStudentDetails(studentId);
        return academicRecordRepository.findByStudentId(studentId);
    }

    public Map<String, Object> generateTranscript(Integer studentId) {
        Student student = studentService.getStudentDetails(studentId);
        List<AcademicRecord> records = academicRecordRepository.findByStudentId(studentId);
        Map<String, Object> transcript = new LinkedHashMap<>();
        transcript.put("studentId", student.getStudentId());
        transcript.put("studentName", student.getName());
        transcript.put("department", student.getDepartment());
        transcript.put("enrollmentYear", student.getEnrollmentYear());
        transcript.put("coursesCompleted", records.size());
        transcript.put("gpa", calculateGpa(records));
        transcript.put("grades", records);
        return transcript;
    }

    public byte[] generatePdf(Integer studentId) {
        Student student = studentService.getStudentDetails(studentId);
        List<AcademicRecord> records = academicRecordRepository.findByStudentId(studentId);
        List<String> lines = new ArrayList<>();
        lines.add("COGNIZANT UNIVERSITY");
        lines.add("OFFICIAL ACADEMIC GRADE SHEET");
        lines.add("");
        lines.add("Student ID      : " + student.getStudentId());
        lines.add("Student Name    : " + student.getName());
        lines.add("Department      : " + label(student.getDepartment().name()));
        lines.add("Enrollment Year : " + student.getEnrollmentYear());
        lines.add("Generated On    : " + LocalDate.now());
        lines.add("");
        lines.add("CODE       COURSE                              SEMESTER       GRADE");
        lines.add("------------------------------------------------------------------");
        for (AcademicRecord record : records) {
            Course course = courseRepository.findById(record.getCourseId()).orElse(null);
            String code = course == null ? String.valueOf(record.getCourseId()) : course.getCourseCode();
            String name = course == null ? "Course " + record.getCourseId() : course.getCourseName();
            lines.add(String.format("%-10s %-35s %-14s %s", trim(code, 10), trim(name, 35),
                    trim(record.getSemester(), 14), record.getGrade()));
        }
        if (records.isEmpty()) lines.add("No completed course grades are available.");
        lines.add("");
        lines.add("Courses Completed: " + records.size());
        lines.add("GPA: " + calculateGpa(records));
        lines.add("");
        lines.add("This grade sheet was generated by the University Academic Management System.");
        return simplePdf(lines);
    }

    private String calculateGpa(List<AcademicRecord> records) {
        double weightedPoints = 0;
        int credits = 0;
        for (AcademicRecord record : records) {
            Double points = GRADE_POINTS.get(record.getGrade().toUpperCase());
            Course course = courseRepository.findById(record.getCourseId()).orElse(null);
            if (points != null && course != null) {
                weightedPoints += points * course.getCredits();
                credits += course.getCredits();
            }
        }
        return credits == 0 ? "N/A" : String.format(Locale.ROOT, "%.2f", weightedPoints / credits);
    }

    private byte[] simplePdf(List<String> lines) {
        StringBuilder content = new StringBuilder("BT\n/F1 10 Tf\n46 756 Td\n14 TL\n");
        for (String line : lines.stream().limit(50).toList()) {
            content.append('(').append(escape(ascii(line))).append(") Tj\nT*\n");
        }
        content.append("ET\n");
        byte[] stream = content.toString().getBytes(StandardCharsets.US_ASCII);
        List<byte[]> objects = List.of(
                bytes("<< /Type /Catalog /Pages 2 0 R >>"),
                bytes("<< /Type /Pages /Kids [3 0 R] /Count 1 >>"),
                bytes("<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>"),
                bytes("<< /Type /Font /Subtype /Type1 /BaseFont /Courier >>"),
                bytes("<< /Length " + stream.length + " >>\nstream\n" + new String(stream, StandardCharsets.US_ASCII) + "endstream")
        );
        ByteArrayOutputStream pdf = new ByteArrayOutputStream();
        write(pdf, "%PDF-1.4\n");
        int[] offsets = new int[objects.size() + 1];
        for (int i = 0; i < objects.size(); i++) {
            offsets[i + 1] = pdf.size();
            write(pdf, (i + 1) + " 0 obj\n");
            pdf.writeBytes(objects.get(i));
            write(pdf, "\nendobj\n");
        }
        int xref = pdf.size();
        write(pdf, "xref\n0 " + (objects.size() + 1) + "\n0000000000 65535 f \n");
        for (int i = 1; i < offsets.length; i++) write(pdf, String.format(Locale.ROOT, "%010d 00000 n \n", offsets[i]));
        write(pdf, "trailer\n<< /Size " + (objects.size() + 1) + " /Root 1 0 R >>\nstartxref\n" + xref + "\n%%EOF");
        return pdf.toByteArray();
    }

    private byte[] bytes(String value) { return value.getBytes(StandardCharsets.US_ASCII); }
    private void write(ByteArrayOutputStream output, String value) { output.writeBytes(bytes(value)); }
    private String ascii(String value) { return value == null ? "" : value.replaceAll("[^\\x20-\\x7E]", "?"); }
    private String escape(String value) { return value.replace("\\", "\\\\").replace("(", "\\(").replace(")", "\\)"); }
    private String trim(String value, int max) { return value == null ? "" : value.substring(0, Math.min(value.length(), max)); }
    private String label(String value) {
        StringJoiner result = new StringJoiner(" ");
        for (String word : value.toLowerCase().split("_")) {
            result.add(Character.toUpperCase(word.charAt(0)) + word.substring(1));
        }
        return result.toString();
    }
}
